# Generated by Django 4.0.6 on 2022-08-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('attendance_time', models.TimeField()),
                ('date', models.DateField()),
                ('late', models.TimeField()),
                ('salary_deduct', models.FloatField()),
            ],
        ),
    ]
