# Generated by Django 4.0.6 on 2022-08-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocketspy', '0002_remove_attendancemodel_late_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancemodel',
            old_name='user',
            new_name='user_name',
        ),
    ]
