# Generated by Django 4.0.6 on 2022-08-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocketspy', '0003_rename_user_attendancemodel_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncodingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
