# Generated by Django 4.0.6 on 2022-08-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocketspy', '0004_faceencodingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceencodingmodel',
            name='name',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
