# Generated by Django 4.1 on 2022-08-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocketspy', '0005_faceencodingmodel_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceEncodingModel',
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='late',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='sal_ded',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendancemodel',
            unique_together={('user_name', 'date')},
        ),
    ]
