# Generated by Django 4.1 on 2022-08-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocketspy', '0006_delete_faceencodingmodel_attendancemodel_late_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('post_code', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('dob', models.DateField()),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('marital_status', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('salary_type', models.CharField(max_length=30)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('date_of_joining', models.DateField()),
                ('elwp', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(max_length=50)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('office_time', models.TimeField()),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
